### ISSUE TITLE
Mess `(TypeError): a is undefined` shown in place of the leaderboard tables

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#164]
https://www.synapse.org/#!Synapse:syn22277123/wiki/608546

Note: I'm presenting the NLP Sandbox at the AMIA 2022 Informatics Summit next week.. :)

**Comment by thomasyu888** [comment]
@tschaffter I think this was a platform bug: https://sagebionetworks.jira.com/browse/SWC-6043.  I think it is fixed as I can see the leaderboard now.  Please close if you also confirm its working.

**Comment by tschaffter** [comment]
I still see the error message and not the leaderboard, at least one the Location Annotation Leaderboard page. Will try again later.

![image](https://user-images.githubusercontent.com/3056480/158491505-6558bff6-60b2-4f64-97b5-98f948e11954.png)

**Comment by thomasyu888** [comment]
@tschaffter, my apologies - I tried in incognito mode and I could reproduce an error.  I think the fix has yet to be deployed?
